-- Baseline IT Skill Taxonomy seed for demo/development.
-- Run AFTER schema.sql. Idempotent by normalized_name.
INSERT INTO skills (name, normalized_name, skill_kind, category, description) VALUES
('Python','python','HARD','Language','Python programming'),
('Java','java','HARD','Language','Java programming'),
('JavaScript','javascript','HARD','Language','JavaScript programming'),
('TypeScript','typescript','HARD','Language','TypeScript programming'),
('C#','csharp','HARD','Language','C# programming'),
('C++','cpp','HARD','Language','C++ programming'),
('SQL','sql','HARD','Database','SQL querying'),
('HTML','html','HARD','Frontend','HTML'),
('CSS','css','HARD','Frontend','CSS'),
('React','react','HARD','Frontend','React'),
('Next.js','nextjs','HARD','Frontend','Next.js'),
('Tailwind CSS','tailwind-css','HARD','Frontend','Tailwind CSS'),
('FastAPI','fastapi','HARD','Backend','FastAPI'),
('Django','django','HARD','Backend','Django'),
('Spring Boot','spring-boot','HARD','Backend','Spring Boot'),
('ASP.NET Core','aspnet-core','HARD','Backend','ASP.NET Core'),
('Node.js','nodejs','HARD','Backend','Node.js'),
('REST API','rest-api','HARD','Backend','RESTful API design'),
('PostgreSQL','postgresql','HARD','Database','PostgreSQL'),
('MySQL','mysql','HARD','Database','MySQL'),
('MongoDB','mongodb','HARD','Database','MongoDB'),
('Redis','redis','HARD','Database','Redis'),
('Git','git','HARD','Tool','Git version control'),
('Docker','docker','HARD','DevOps','Docker'),
('Linux','linux','HARD','DevOps','Linux'),
('CI/CD','cicd','HARD','DevOps','Continuous Integration/Delivery'),
('AWS','aws','HARD','Cloud','Amazon Web Services'),
('Azure','azure','HARD','Cloud','Microsoft Azure'),
('Machine Learning','machine-learning','HARD','AI','Machine Learning'),
('Deep Learning','deep-learning','HARD','AI','Deep Learning'),
('Natural Language Processing','nlp','HARD','AI','Natural Language Processing'),
('Sentence Transformers','sentence-transformers','HARD','AI','Sentence Transformers'),
('PyTorch','pytorch','HARD','AI','PyTorch'),
('TensorFlow','tensorflow','HARD','AI','TensorFlow'),
('Pandas','pandas','HARD','Data','Pandas'),
('NumPy','numpy','HARD','Data','NumPy'),
('Communication','communication','SOFT','Communication','Communication skill'),
('Teamwork','teamwork','SOFT','Communication','Teamwork'),
('Problem Solving','problem-solving','SOFT','Professional','Problem solving'),
('Time Management','time-management','SOFT','Professional','Time management'),
('Critical Thinking','critical-thinking','SOFT','Professional','Critical thinking'),
('Leadership','leadership','SOFT','Professional','Leadership')
ON CONFLICT (normalized_name) DO NOTHING;
